<?php
$DATA=array (
  'BDSTRUCTURE' => 
  array (
    'data' => 
    array (
      0 => 'CREATE TABLE `data` (
`id` INT(11)  NOT NULL auto_increment ,
`url` VARCHAR(450) character set utf8 collate utf8_general_ci    default NULL ,
`enable` BOOL     default \'1\' ,
 `page_id` int(11) default NULL,
 `tag_id` int(11) default NULL,
 `lang_id` int(11) default NULL,
 `sort_index` bigint default \'0\' 
, PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

',
    ),
    'urls' => 
    array (
      0 => 'CREATE TABLE `urls` (
`id` INT(11)  NOT NULL auto_increment ,
`url` VARCHAR(450) character set utf8 collate utf8_general_ci    default NULL ,
`used` BOOL     default \'0\' ,
 `page_id` int(11) default NULL,
 `tag_id` int(11) default NULL,
 `lang_id` int(11) default NULL,
 `sort_index` bigint default \'0\' 
, PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

',
    ),
  ),
  'BLOCKS' => 
  array (
    0 => 
    array (
      'id' => '1586',
      'module_id' => '357',
      'type' => '2',
      'name' => 'ShowSiteMap',
      'description' => 'Карта сайта',
      'act_variable' => 'act',
      'act_method' => 'get',
      'url_get_vars' => '',
      'general_table_id' => '1801',
      'loaded_name' => 'ShowSiteMap',
      'sort_index' => '596',
      'settings' => 
      array (
        0 => 
        array (
          'id' => '176',
          'block_id' => '1586',
          'name' => '_blank',
          'value' => '0',
          'description' => 'При клике на ссылку открывать страницу в новом окне',
          'edit_s_type_id' => '3',
          'loaded_name' => '_blank',
        ),
      ),
      'templates' => 
      array (
        0 => 
        array (
          'id' => '73',
          'block_id' => '1586',
          'name' => 'show_sitemap.tpl',
          'description' => 'Вывод карты сайта',
          'content' => '',
          'loaded_name' => 'show_sitemap.tpl',
          'sort_index' => '1004',
          'block_name' => 'ShowSiteMap',
        ),
      ),
    ),
    1 => 
    array (
      'id' => '1587',
      'module_id' => '357',
      'type' => '2',
      'name' => 'GenerateGoogleSitemap',
      'description' => 'Генерация sitemap.xml',
      'act_variable' => 'act',
      'act_method' => 'get',
      'url_get_vars' => '',
      'general_table_id' => '0',
      'loaded_name' => 'GenerateGoogleSitemap',
      'sort_index' => '1587',
      'settings' => 
      array (
      ),
      'templates' => 
      array (
        0 => 
        array (
          'id' => '74',
          'block_id' => '1587',
          'name' => 'show_list.tpl',
          'description' => 'Генерация sitemap.xml',
          'content' => '',
          'loaded_name' => 'show_list.tpl',
          'sort_index' => '74',
          'block_name' => 'GenerateGoogleSitemap',
        ),
        1 => 
        array (
          'id' => '75',
          'block_id' => '1587',
          'name' => 'res.tpl',
          'description' => 'Результат генерации карты сайта',
          'content' => '',
          'loaded_name' => 'res.tpl',
          'sort_index' => '75',
          'block_name' => 'GenerateGoogleSitemap',
        ),
        2 => 
        array (
          'id' => '76',
          'block_id' => '1587',
          'name' => 'process.tpl',
          'description' => 'Процесс построения карты',
          'content' => '',
          'loaded_name' => 'process.tpl',
          'sort_index' => '76',
          'block_name' => 'GenerateGoogleSitemap',
        ),
      ),
    ),
  ),
  'TABLES' => 
  array (
    0 => 
    array (
      'id' => '1801',
      'module_id' => '357',
      'name' => 'data',
      'description' => 'Список запрещённых страниц',
      'show_type' => '1',
      'additional_buttons' => 'Сгенерировать sitemap.xml::GenerateGoogleSitemap',
      'loaded_name' => 'data',
      'sort_index' => '1138',
      'table_name' => 'data',
      'fields_settings' => 
      array (
        0 => 
        array (
          'id' => '770',
          'field_id' => '770',
          'active' => '0',
          'show_in_list' => '0',
          'filter' => '0',
          'check_regular_id' => '0',
          'regex_other' => '',
          'height' => '',
          'width' => '',
          'style' => '',
          'hide_by_field' => '0',
          'hide_operator' => '0',
          'hide_on_value' => '',
          'avator_quality' => '0',
          'avator_width' => '0',
          'avator_height' => '0',
          'avator_quality_big' => '0',
          'avator_width_big' => '0',
          'avator_height_big' => '0',
          'regex' => NULL,
          'edittype_id' => '0',
          'fieldname' => 'id',
          'comment' => 'id',
          'sourse_field_id' => '0',
          'delete' => '0',
          'own_filter' => '0',
          'datatype_id' => '7',
          'len' => '11',
          'default' => '',
          'collation_id' => '0',
          'group_caption' => '',
          'not_null' => '1',
          'unsigned' => '0',
          'auto_incr' => '1',
          'zerofill' => '0',
          'unique' => '0',
          'notfedit' => '0',
          'pk' => '1',
          'sort_index' => '100',
          'table_name' => 'data',
          'sourse_field_name' => '',
          'sourse_table_name' => '',
          'hide_by_field_caption' => '',
        ),
        1 => 
        array (
          'id' => '771',
          'field_id' => '771',
          'active' => '1',
          'show_in_list' => '1',
          'filter' => '1',
          'check_regular_id' => '0',
          'regex_other' => '',
          'height' => '',
          'width' => '',
          'style' => '',
          'hide_by_field' => '0',
          'hide_operator' => '0',
          'hide_on_value' => '',
          'avator_quality' => '0',
          'avator_width' => '0',
          'avator_height' => '0',
          'avator_quality_big' => '0',
          'avator_width_big' => '0',
          'avator_height_big' => '0',
          'regex' => NULL,
          'edittype_id' => '5',
          'fieldname' => 'enable',
          'comment' => 'Не выводить в карту',
          'sourse_field_id' => '0',
          'delete' => '0',
          'own_filter' => '0',
          'datatype_id' => '27',
          'len' => '',
          'default' => '1',
          'collation_id' => '0',
          'group_caption' => '1',
          'not_null' => '0',
          'unsigned' => '0',
          'auto_incr' => '0',
          'zerofill' => '0',
          'unique' => '0',
          'notfedit' => '0',
          'pk' => '0',
          'sort_index' => '70',
          'table_name' => 'data',
          'sourse_field_name' => '',
          'sourse_table_name' => '',
          'hide_by_field_caption' => '',
        ),
        2 => 
        array (
          'id' => '776',
          'field_id' => '776',
          'active' => '1',
          'show_in_list' => '1',
          'filter' => '0',
          'check_regular_id' => '0',
          'regex_other' => NULL,
          'height' => NULL,
          'width' => NULL,
          'style' => NULL,
          'hide_by_field' => '0',
          'hide_operator' => 0,
          'hide_on_value' => NULL,
          'avator_quality' => '100',
          'avator_width' => '150',
          'avator_height' => '150',
          'avator_quality_big' => '100',
          'avator_width_big' => '800',
          'avator_height_big' => '600',
          'regex' => NULL,
          'edittype_id' => '1',
          'fieldname' => 'url',
          'comment' => 'Запрещённый URL',
          'sourse_field_id' => '0',
          'delete' => '0',
          'own_filter' => '0',
          'datatype_id' => '1',
          'len' => '450',
          'default' => '',
          'collation_id' => '56',
          'group_caption' => '',
          'not_null' => '0',
          'unsigned' => '0',
          'auto_incr' => '0',
          'zerofill' => '0',
          'unique' => '0',
          'notfedit' => '0',
          'pk' => '0',
          'sort_index' => '80',
          'table_name' => 'data',
          'sourse_field_name' => '',
          'sourse_table_name' => '',
          'hide_by_field_caption' => '',
        ),
      ),
    ),
    1 => 
    array (
      'id' => '1802',
      'module_id' => '357',
      'name' => 'urls',
      'description' => 'Временные ссылки',
      'show_type' => '0',
      'additional_buttons' => '',
      'loaded_name' => 'urls',
      'sort_index' => '1802',
      'table_name' => 'urls',
      'fields_settings' => 
      array (
        0 => 
        array (
          'id' => '773',
          'field_id' => '773',
          'active' => '0',
          'show_in_list' => '0',
          'filter' => '0',
          'check_regular_id' => '0',
          'regex_other' => '',
          'height' => '',
          'width' => '',
          'style' => '',
          'hide_by_field' => '0',
          'hide_operator' => '0',
          'hide_on_value' => '',
          'avator_quality' => '0',
          'avator_width' => '0',
          'avator_height' => '0',
          'avator_quality_big' => '0',
          'avator_width_big' => '0',
          'avator_height_big' => '0',
          'regex' => NULL,
          'edittype_id' => '0',
          'fieldname' => 'id',
          'comment' => 'id',
          'sourse_field_id' => '0',
          'delete' => '0',
          'own_filter' => '0',
          'datatype_id' => '7',
          'len' => '11',
          'default' => '',
          'collation_id' => '0',
          'group_caption' => NULL,
          'not_null' => '1',
          'unsigned' => '0',
          'auto_incr' => '1',
          'zerofill' => '0',
          'unique' => '0',
          'notfedit' => '0',
          'pk' => '1',
          'sort_index' => '100',
          'table_name' => 'urls',
          'sourse_field_name' => '',
          'sourse_table_name' => '',
          'hide_by_field_caption' => '',
        ),
        1 => 
        array (
          'id' => '774',
          'field_id' => '774',
          'active' => '1',
          'show_in_list' => '1',
          'filter' => '0',
          'check_regular_id' => '0',
          'regex_other' => NULL,
          'height' => NULL,
          'width' => NULL,
          'style' => NULL,
          'hide_by_field' => '0',
          'hide_operator' => 0,
          'hide_on_value' => NULL,
          'avator_quality' => '100',
          'avator_width' => '150',
          'avator_height' => '150',
          'avator_quality_big' => '100',
          'avator_width_big' => '800',
          'avator_height_big' => '600',
          'regex' => NULL,
          'edittype_id' => '1',
          'fieldname' => 'url',
          'comment' => 'Ссылка',
          'sourse_field_id' => '0',
          'delete' => '0',
          'own_filter' => '0',
          'datatype_id' => '1',
          'len' => '450',
          'default' => '',
          'collation_id' => '56',
          'group_caption' => NULL,
          'not_null' => '0',
          'unsigned' => '0',
          'auto_incr' => '0',
          'zerofill' => '0',
          'unique' => '0',
          'notfedit' => '0',
          'pk' => '0',
          'sort_index' => '90',
          'table_name' => 'urls',
          'sourse_field_name' => '',
          'sourse_table_name' => '',
          'hide_by_field_caption' => '',
        ),
        2 => 
        array (
          'id' => '775',
          'field_id' => '775',
          'active' => '1',
          'show_in_list' => '1',
          'filter' => '0',
          'check_regular_id' => '0',
          'regex_other' => NULL,
          'height' => NULL,
          'width' => NULL,
          'style' => NULL,
          'hide_by_field' => '0',
          'hide_operator' => 0,
          'hide_on_value' => NULL,
          'avator_quality' => '100',
          'avator_width' => '150',
          'avator_height' => '150',
          'avator_quality_big' => '100',
          'avator_width_big' => '800',
          'avator_height_big' => '600',
          'regex' => NULL,
          'edittype_id' => '5',
          'fieldname' => 'used',
          'comment' => 'Была использована',
          'sourse_field_id' => '0',
          'delete' => '0',
          'own_filter' => '0',
          'datatype_id' => '27',
          'len' => '',
          'default' => '0',
          'collation_id' => '0',
          'group_caption' => NULL,
          'not_null' => '0',
          'unsigned' => '0',
          'auto_incr' => '0',
          'zerofill' => '0',
          'unique' => '0',
          'notfedit' => '0',
          'pk' => '0',
          'sort_index' => '80',
          'table_name' => 'urls',
          'sourse_field_name' => '',
          'sourse_table_name' => '',
          'hide_by_field_caption' => '',
        ),
      ),
    ),
  ),
  'MODULE' => 
  array (
    'id' => '357',
    'name' => 'Sitemap',
    'version' => '1',
    'description' => 'Карта сайта',
    'loaded' => '1',
    'need_save' => '0',
    'loaded_name' => 'Sitemap',
    'sort_index' => '357',
  ),
);
?>